### ISSUE TITLE
Not really a bug

### ISSUE THREAD

**Issue by Batzuga** [Batzuga/BugReporterTest#54]
```yaml
Area: Other
Content: This is not actually a bug, but a test to show how the text is formated on Discord`s side.
All additional data currently built in is sent and can be seen here.
Reported By: Batzuga


System Info: 
Device Type: Desktop
OS Family: Windows
OS: Windows 10  (10.0.19043) 64bit
GPU: NVIDIA GeForce GTX 1080
GPU Memory: 8079
GPU Vendor: NVIDIA
GPU Version: Direct3D 11.0 [level 11.1]
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
RAM: 32680


Level Info: 
Scene: GameScene
Game Version: 0.1
Time Stamp: 13.3.2022 0.26.53
```
