### ISSUE TITLE
Test Bug from Editor

### ISSUE THREAD

**Issue by Batzuga** [Batzuga/BugReporterTest#70]
```yaml
Area: Gameplay
Content: Testing the content too.
Reported By: Batzuga


System Info: 
Device Type: Desktop
OS Family: Windows
OS: Windows 10  (10.0.0) 64bit
GPU: NVIDIA GeForce GTX 1080
GPU Memory: 8079
GPU Vendor: NVIDIA
GPU Version: Direct3D 11.0 [level 11.1]
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
RAM: 32680


Extra Info: 
Scene: SampleScene
Game Version: 0.1
Time Stamp: 18.3.2022 12.30.29
```
